/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import api.connector.desktopapp.APIConnectorDesktopApp;
import api.connector.desktopapp.connectors.HttpRequestsCon;

/**
 *
 * @author senura
 */
public class TaskReportWindow extends javax.swing.JFrame {

    /**
     * Creates new form TaskReportWindow
     */
    public TaskReportWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField_endpoint = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_output = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jButton_get = new javax.swing.JButton();
        jButton_post = new javax.swing.JButton();
        jButton_post1 = new javax.swing.JButton();
        jButton_post2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_ReqPayload = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 600));
        setMinimumSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel1.setText("API Caller - IMAGINARy");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 0, 440, 70);

        jTextField_endpoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_endpointActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_endpoint);
        jTextField_endpoint.setBounds(190, 110, 198, 49);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setText("API endpoint");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(230, 70, 151, 53);

        jTextArea_output.setColumns(20);
        jTextArea_output.setRows(5);
        jScrollPane1.setViewportView(jTextArea_output);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 400, 570, 154);

        jLabel7.setText("Output");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(270, 370, 50, 16);

        jButton_get.setText("GET");
        jButton_get.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_getActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_get);
        jButton_get.setBounds(90, 330, 65, 35);

        jButton_post.setText("POST");
        jButton_post.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_postActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_post);
        jButton_post.setBounds(190, 330, 65, 35);

        jButton_post1.setText("PUT");
        jButton_post1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_post1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_post1);
        jButton_post1.setBounds(290, 330, 65, 35);

        jButton_post2.setText("DELETE");
        jButton_post2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_post2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_post2);
        jButton_post2.setBounds(390, 330, 100, 35);

        jTextArea_ReqPayload.setColumns(20);
        jTextArea_ReqPayload.setRows(5);
        jScrollPane2.setViewportView(jTextArea_ReqPayload);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 220, 540, 90);

        jLabel8.setText("Request Payload");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(250, 200, 102, 16);

        jLabel2.setText("Eg. http://localhost:5000/api/projects/track/2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 150, 310, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_getActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_getActionPerformed
       
        HttpRequestsCon httpCon=new HttpRequestsCon();
        APIConnectorDesktopApp.callGET(httpCon, jTextField_endpoint.getText());
        
    }//GEN-LAST:event_jButton_getActionPerformed

    private void jButton_postActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_postActionPerformed
         HttpRequestsCon httpCon=new HttpRequestsCon();
        APIConnectorDesktopApp.callPOST(httpCon, jTextField_endpoint.getText(),jTextArea_ReqPayload.getText());
        
    }//GEN-LAST:event_jButton_postActionPerformed

    private void jButton_post1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_post1ActionPerformed
        HttpRequestsCon httpCon=new HttpRequestsCon();
        APIConnectorDesktopApp.callPUT(httpCon, jTextField_endpoint.getText(),jTextArea_ReqPayload.getText());
        
    }//GEN-LAST:event_jButton_post1ActionPerformed

    private void jButton_post2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_post2ActionPerformed
        
        HttpRequestsCon httpCon=new HttpRequestsCon();
        APIConnectorDesktopApp.callDelete(httpCon, jTextField_endpoint.getText());
         
    }//GEN-LAST:event_jButton_post2ActionPerformed

    private void jTextField_endpointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_endpointActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_endpointActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaskReportWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaskReportWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaskReportWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaskReportWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TaskReportWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_get;
    private javax.swing.JButton jButton_post;
    private javax.swing.JButton jButton_post1;
    private javax.swing.JButton jButton_post2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTextArea jTextArea_ReqPayload;
    public static javax.swing.JTextArea jTextArea_output;
    private javax.swing.JTextField jTextField_endpoint;
    // End of variables declaration//GEN-END:variables
}
